"""initial schema

Revision ID: 61ff98b27d3e
Revises: 
Create Date: 2026-10-03 01:00:39.440848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ff98b27d3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('footprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_km', sa.Float(), nullable=False),
    sa.Column('electricity_kwh', sa.Float(), nullable=False),
    sa.Column('meat_meals', sa.Integer(), nullable=False),
    sa.Column('plant_meals', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('factors_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('footprint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_footprint_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_footprint_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_footprint_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('footprint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_footprint_user_id'))
        batch_op.drop_index(batch_op.f('ix_footprint_region'))
        batch_op.drop_index(batch_op.f('ix_footprint_created_at'))

    op.drop_table('footprint')
    op.drop_table('user')
    # ### end Alembic commands ###
